invalid_grant:
  error_code: 401_001
  error_message: invalid grant
login_required:
  error_code: 401_030
  error_message: member need login first
member_auth_failed:
  app_code: 401
  error_code: 401_202
  error_message: member auth failed
token_invalid:
  error_code: 401_203
  error_message: token is invalid
password_not_match:
  error_code: 401_204
  error_message: password not match
password_invalid:
  error_code: 401_205
  error_message: password is invalid
callback_url_invalid:
  error_code: 401_206
  error_message: callback url is invalid
api_key_invalid:
  error_code: 401_207
  error_message: unrecognized api_key, please make sure your plan is enterprise and your subscription hasn't expired
invalid_member_use_standard_api:
  error_code: 401_208
  error_message: member token is not accessable for using standard api, please check your token and make sure token is obtain by login api
session_logged_out:
  error_code: 401_209
  error_message: session has been logged out
auth_code_invalid:
  error_code: 401_210
  error_message: authorization code is invalid
login_code_invalid:
  error_code: 401_210
  error_message: login_code is invalid
account_suspended:
  error_code: 401_211
  error_message: account suspended
invalid_session:
  error_code: 401_212
  error_message: session is blank or undefined
session_expired:
  error_code: 401_213
  error_message: session that generated the access_token has already expired
authorize_failed:
  error_code: 401_401
  error_message: Authorize failed