invalid_grant:
  error_code: 401_001
  error_message: invalid grant, or refresh token was revoked
doorkeeper_access_token_expired:
  error_code: 401_002
  error_message: doorkeeper access token expired
doorkeeper_access_token_unauthorization:
  error_code: 401_003
  error_message: doorkeeper access token is unauthorization
login_required:
  error_code: 401_030
  error_message: member need login first  
member_auth_failed:
  app_code: 401
  error_code: 401_202
  error_message: member auth failed
token_invalid:
  error_code: 401_203
  error_message: token is invalid
password_not_match:
  error_code: 401_204
  error_message: password not match
password_invalid:
  error_code: 401_205
  error_message: password is invalid
authorize_failed:
  error_code: 401_401
  error_message: Authorize failed