signature_not_found:
  app_code: 4002
  error_code: 404_030
  error_message: signature not found
task_not_found:
  app_code: 4004
  error_code: 404_031
  error_message: task not found
stage_not_found:
  app_code: 4006
  error_code: 404_032
  error_message: stage not found
verify_source_not_set:
  error_code: 404_033
  error_message: verify source not set
signer_not_found:
  error_code: 404_034
  error_message: signer not found
template_not_found:
  error_code: 404_035
  error_message: template not found
attachment_setting_not_found:
  error_code: 404_036
  error_message: attachment setting not found
tag_not_found:
  error_code: 404_037
  error_message: tag not found
file_not_found:
  error_code: 404_038
  error_message: file not found
page_not_found:
  error_code: 404_039
  error_message: page not found
mission_not_found:
  error_code: 404_040
  error_message: mission not found
taggable_not_found:
  error_code: 404_041
  error_message: taggable type not found
decline_option_not_found:
  error_code: 404_042
  error_message: decline option not found
form_not_found:
  error_code: 404_043
  error_message: public form not found
coupon_not_found:
  error_code: 404_100
  error_message: coupon not found
voucher_not_found:
  error_code: 404_101
  error_message: voucher not found
subscription_not_found:
  error_code: 404_103
  error_message: subscription not found
plan_not_found:
  error_code: 404_104
  error_message: plan not found
event_not_found:
  error_code: 404_105
  error_message: event not found
card_token_not_found:
  error_code: 404_106
  error_message: card token not found
invoice_not_found:
  error_code: 404_107
  error_message: invoice not found
payment_not_found:
  error_code: 404_108
  error_message: payment not found
member_not_found:
  error_code: 404_201
  error_message: member not found
contact_not_exist:
  error_code: 404_202
  error_message: contact not exist
provider_not_exist:
  error_code: 404_203
  error_message: provider not exist
register_not_found:
  error_code: 404_204
  error_message: register not found
group_not_found:
  error_code: 404_205
  error_message: group not found
profile_not_found:
  error_code: 404_206
  error_message: no such member profiles
org_detail_not_found:
  error_code: 404_207
  error_message: org detail not found
client_not_found:
  error_code: 404_208
  error_message: client not found
info_not_found:
  error_code: 404_209
  error_message: info not found
product_not_found:
  error_code: 404_301
  error_message: product not found
credit_record_not_found:
  error_code: 404_302
  error_message: credit record not found
request_link_not_found:
  error_code: 404_401
  error_message: Request link not found or expired
file_or_folder_not_found:
  error_code: 404_402
  error_message: Target file or folder not found
team_not_found:
  error_code: 404_403
  error_message: Target team not found
share_link_not_found:
  error_code: 404_404
  error_message: Share link not found
scope_object_not_found:
  error_code: 404_405
  error_message: Scope object not found
target_user_not_found:
  error_code: 404_406
  error_message: Target user not found
bundle_id_not_found:
  error_code: 404_501
  error_message: app bundle_id is not found or not accessible
default_message_not_found:
  error_code: 404_502
  error_message: default message is not found or not accessible
video_not_found:
  error_code: 404_601
  error_message: video not found
user_not_found:
  error_code: 404_603
  error_message: user not found
report_not_found:
  error_code: 404_604
  error_message: report not found
note_not_found:
  error_code: 404_1001
  error_message: note not found
card_not_found:
  error_code: 404_1002
  error_message: card not found
favorite_not_found:
  error_code: 404_1003
  error_message: favorite not found
credit_mission_not_found:
  error_code: 404_1101
  error_message: credit mission not found
license_not_found:
  error_code: 404_1201
  error_message: license not found
invite_not_found:
  error_code: 404_1301
  error_message: invite not found
