happy_tree_friend_key:
  error_code: 418_003
  error_message: happy tree friend
subscription_expired:
  error_code: 410_301
  error_message: Your subscription has expired. Please re-subscribe at Kdan Creative Store to continue assigning licenses
incorrect_info:
  error_code: 422_001
  error_message: Incorrect email or password
incorrect_info_and_unconfirm:
  error_code: 422_002
  error_message: Incorrect email or password; Email not confirm yes
domain_rejected:
  error_code: 431_001
  error_message: This domain is rejected
domain_not_verified:
  error_code: 433_001
  error_message: This domain has not been verified
user_already_subscribed:
  error_code: 434_001
  error_message: This domain is verified but user already subscribed
internal_server_error:
  error_code: 500_000
  error_message: internal server error